### PR TITLE
test: upgrade cypress to version 10

### LINKED ISSUE #282: Upgrade Cypress version
Upgrade to Cypress version 10

### PR DESCRIPTION
**Pull request by jtsang586**
closes #282 

- Upgrade to Cypress 10
- Fix failing tests in CI
- Added assertions to asset test

### CODE REVIEW

**Review by dexturr — CHANGES_REQUESTED** [review]
Code coverage has been broken as part of this, ideally I'd like us to keep the setup if we can

**Comment by jtsang586** [comment]
> Code coverage has been broken as part of this, ideally I'd like us to keep the setup if we can

The coverage report should be running now

**Review by mattrussell36 — APPROVED** [review]
Looks good, other than the test coverage, which Dex mentioned

**Comment by jtsang586** [comment]
Created new ticket for the code coverage report not working 
https://github.com/vegaprotocol/vegawallet-desktop/issues/285

**Review by dexturr — APPROVED** [review]

**Pull request merged**
